### ISSUE TITLE
Does not compile against development version of RDKit

### ISSUE THREAD

**Issue by markussitzmann** [nextmovesoftware/molhash#1] opened 2019-05-30 22:27 UTC
Hi Noel,

unfortunately it doesn't build for me, the following Dockerfile building rdkit and then molhash fails

https://github.com/markussitzmann/molhash/blob/master/Dockerfile

docker build . -t molhash

Can you maybe take a look, please?

Thanks,
Markus

**Log:**

Step 17/18 : RUN cmake     ..
 ---> Running in 7507b63b7e15
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found RDKit include files at /opt/rdkit/Code
-- Found RDKit libraries at /opt/rdkit/lib
-- Targeting RDKit toolkit
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found Threads: TRUE  
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- The RDKit version is 20190302
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/molhash/build
Removing intermediate container 7507b63b7e15
 ---> bd5193cf8129
Step 18/18 : RUN make -j $(nproc)
 ---> Running in 50ced4382df8
Scanning dependencies of target molhashlib
[ 33%] Building CXX object CMakeFiles/molhashlib.dir/normalize.cpp.o
[ 33%] Building CXX object CMakeFiles/molhashlib.dir/hashfunctions.cpp.o
[ 50%] Building CXX object CMakeFiles/molhashlib.dir/rdktoolkit.cpp.o
[ 66%] Linking CXX static library libmolhashlib.a
[ 66%] Built target molhashlib
Scanning dependencies of target molhash
[ 83%] Building CXX object CMakeFiles/molhash.dir/molhash.cpp.o
[100%] Linking CXX executable molhash
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `boost::any::holder<ExplicitBitVect>::type() const':
MolPickler.cpp:(.text._ZNK5boost3any6holderI15ExplicitBitVectE4typeEv[_ZNK5boost3any6holderI15ExplicitBitVectE4typeEv]+0x3): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `boost::any::holder<ExplicitBitVect>::clone() const':
MolPickler.cpp:(.text._ZNK5boost3any6holderI15ExplicitBitVectE5cloneEv[_ZNK5boost3any6holderI15ExplicitBitVectE5cloneEv]+0x2d): undefined reference to `ExplicitBitVect::ExplicitBitVect(ExplicitBitVect const&)'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `RDKit::SubstanceGroup::SubstanceGroup(RDKit::SubstanceGroup const&)':
MolPickler.cpp:(.text._ZN5RDKit14SubstanceGroupC2ERKS0_[_ZN5RDKit14SubstanceGroupC5ERKS0_]+0x8ad): undefined reference to `ExplicitBitVect::ExplicitBitVect(ExplicitBitVect const&)'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `ExplicitBitVect const& boost::any_cast<ExplicitBitVect const&>(boost::any&)':
MolPickler.cpp:(.text._ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE[_ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE]+0x28): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE[_ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE]+0x6a): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE[_ZN5boost8any_castIRK15ExplicitBitVectEET_RNS_3anyE]+0x75): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `RDKit::streamWriteProp(std::ostream&, RDKit::Dict::Pair const&, std::vector<std::shared_ptr<RDKit::CustomPropHandler const>, std::allocator<std::shared_ptr<RDKit::CustomPropHandler const> > > const&)':
MolPickler.cpp:(.text._ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE[_ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE]+0x513): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE[_ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE]+0x59b): undefined reference to `typeinfo for ExplicitBitVect'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o):MolPickler.cpp:(.text._ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE[_ZN5RDKit15streamWritePropERSoRKNS_4Dict4PairERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS9_EE]+0x613): more undefined references to `typeinfo for ExplicitBitVect' follow
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `RDKit::DataStructsExplicitBitVecPropHandler::read(std::istream&, RDKit::RDValue&) const':
MolPickler.cpp:(.text._ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE[_ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE]+0x42): undefined reference to `ExplicitBitVect::ExplicitBitVect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: MolPickler.cpp:(.text._ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE[_ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE]+0x77): undefined reference to `ExplicitBitVect::ExplicitBitVect(ExplicitBitVect const&)'
/usr/bin/ld: MolPickler.cpp:(.text._ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE[_ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE]+0x9c): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
/usr/bin/ld: MolPickler.cpp:(.text._ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE[_ZNK5RDKit36DataStructsExplicitBitVecPropHandler4readERSiRNS_7RDValueE]+0xe0): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `boost::any::holder<ExplicitBitVect>::~holder()':
MolPickler.cpp:(.text._ZN5boost3any6holderI15ExplicitBitVectED2Ev[_ZN5boost3any6holderI15ExplicitBitVectED5Ev]+0x14): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `boost::any::holder<ExplicitBitVect>::~holder()':
MolPickler.cpp:(.text._ZN5boost3any6holderI15ExplicitBitVectED0Ev[_ZN5boost3any6holderI15ExplicitBitVectED5Ev]+0x18): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
/usr/bin/ld: /opt/rdkit/lib/libRDKitGraphMol_static.a(MolPickler.cpp.o): in function `RDKit::streamReadProps(std::istream&, RDKit::RDProps&, std::vector<std::shared_ptr<RDKit::CustomPropHandler const>, std::allocator<std::shared_ptr<RDKit::CustomPropHandler const> > > const&)':
MolPickler.cpp:(.text._ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE[_ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE]+0x7e8): undefined reference to `ExplicitBitVect::ExplicitBitVect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE[_ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE]+0x81f): undefined reference to `ExplicitBitVect::ExplicitBitVect(ExplicitBitVect const&)'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE[_ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE]+0x85d): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
/usr/bin/ld: MolPickler.cpp:(.text._ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE[_ZN5RDKit15streamReadPropsERSiRNS_7RDPropsERKSt6vectorISt10shared_ptrIKNS_17CustomPropHandlerEESaIS7_EE]+0xb0e): undefined reference to `ExplicitBitVect::~ExplicitBitVect()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/molhash.dir/build.make:98: molhash] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/molhash.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c make -j $(nproc)' returned a non-zero code: 2

**Comment by baoilleach** [comment] 2019-05-31 08:46
Sorry Markus - support is not provided. However, I can tell you that it worked for me with RDKit 2018.09 and MSVC 2017. As new versions of RDKit come out, the RDKit libraries are renamed or new ones become required dependencies, and so existing build scripts stop working.

**Comment by baoilleach** [comment] 2019-05-31 10:58
On second thoughts, I *will* look into this. If I understand correctly, you are compiling against the latest revision of the 2019.03 branch of RDKit.

**Comment by mcs07** [comment] 2019-05-31 11:27
I just made a conda recipe (https://github.com/mcs07/conda-recipes/commit/0bb180711ea3fd31ae953feadfba1141956f92c2) and it builds fine for me with RDKit 2019.03.2. 
It should now be possible to run `conda install -c mcs07 -c conda-forge molhash` for those who want to install without compiling.

**Comment by markussitzmann** [comment] 2019-05-31 13:16
Thanks, Noel and Matt. 

@Noel: Yes, I tried to compile against the latest revision of RDKit

@Matt: I still don't see what kind of magic you are doing there for molhash. However, I very much like your conda-recipe repository (which I wasn't aware about yet) ... it looks like it resolves a lot of things I had on my plan to tackle but hate to do :-)

**Comment by markussitzmann** [comment] 2019-06-02 14:49
Well, I tried quite a few things. The Dockerfile (I updated it a tiny bit) creates a runnable executable if I compile against RDKit 2018.09; it still fails against RDKit 2019.03 (only change: I flip ENV line comments in line 5 and 6). 

Matt's solution also works for me, I don't know why it fails with my Dockerfile - but I am happy for the time-being :-)

**Comment by baoilleach** [comment] 2019-06-02 18:59
Matt is the using the latest release, 2019.03.2. You are using a version
that has not yet been released, that will become 2019.03.3.

**Comment by markussitzmann** [comment] 2019-06-03 23:10
Even when I use the tagged release (2019.03.2, 2019.03.1), it doesn't build for me .... only 2018.09 ...

**Comment by baoilleach** [comment] 2019-06-04 08:50
Ok - now that's strange.

**Comment by baoilleach** [comment] 2019-06-12 16:08
Can you try again with the latest version (of molhash)? We now need to link against the RDKitDataStructs lib.

**Comment by baoilleach** [comment] 2019-07-03 15:43
Marking as closed. Feel free to reopen @markussitzmann if the issue is unresolved.

**Closed as completed by baoilleach** 2019-07-03 15:43 UTC

**Comment by markussitzmann** [comment] 2019-07-08 20:33
Hi Noel,

sorry, during my vacation I lost this from my radar a bit - nevertheless, I just tried it again, **it compiles now with RDKit 2019.03.**

Thanks a lot for your efforts!

Markus
